### ISSUE TITLE
hope to enhance the optimization for e-ink display devices

### ISSUE THREAD

**Issue by CCbugCC** [mihonapp/mihon#1070]
### Describe your suggested feature

I hope to increase optimization of ink screen equipment, such as:
1. There is a switch that can cancel all animations in the software;
2. The bookshelf/Manga list can support pagination sliding without animation effects;
Thank you all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
E ink options already exist for the reader. 
The e-ink androids I've seen are able to swipe through the library without issue. But instead of creating a setting in the app, you can always just disable animations in developer settings.
![Screenshot_20240801_165506_Settings](https://github.com/user-attachments/assets/17709b29-2708-4706-a2b7-048b4ba7f199)
Note: there will still be a slight animation if you swipe between categories. But it should be skipped if you use the icons at the top to switch.

And I'm sorry subdividing categories into pages seems like the stupidest ideas. Just create more categories 🤣

**Comment by CCbugCC** [comment]
好的，已收到，稍后我会进行查看，感谢来信
