### ISSUE TITLE
Auto-Update Not Reflecting New Manga Chapters

### ISSUE THREAD

**Issue by Angel-dash** [mihonapp/mihon#1175]
### Steps to reproduce

Set Auto-Update: Ensure auto-update is enabled in the app settings, with a frequency of 12 hours.
Wait for Auto-Update: Allow 12 hours to pass, ensuring no manual updates or refreshes are performed during this time.
Check for New Manga: Open the app and navigate to a manga that has received new chapters within the past 12 hours.

### Expected behavior

Upon auto-update, the app should automatically display the new manga chapters for the selected manga.

### Actual behavior

The auto-update does not reflect the new manga chapters. Users must manually open the manga and refresh the page to view the updated content.

### Mihon version

0.16.5

### Android version

Android 14

### Device

Samsung a15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Sounds like it's working as intended, that's just Smart Updates reducing unnecessary requests & spreading out your Library Updates over a predicted release pattern, read more about it here: https://mihon.app/docs/faq/updates/smart

Leave it alone, let it update by itself, and it'll adapt over time. If there's something you really want to read & know it got an update, then manually refresh the entry yourself. Otherwise, this feature reduces the chance of sources blocking you, breaking your extensions, and/or go after whoever maintains your extensions/the app itself.
