### ISSUE TITLE
Image won't show and only background is seen.

### ISSUE THREAD

**Issue by ChanchanReal** [mihonapp/mihon#1388]
### Steps to reproduce

Only works properly on random Manga/Manhua/Manhwa chapters the rest is broken. happens after updating to new version.
![ezgif-6-6040c32355](https://github.com/user-attachments/assets/39a0d3f7-9227-414f-9a2f-92039d2c2538)

### Expected behavior

Should show Image and not the background.

### Actual behavior

Image won't show even if it shows some parts disappear. it works properly before updating to the new version

### Mihon version

0.17.0

### Android version

Android 

### Device

Bluestack samsung s22 ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
I'm guessing here, but maybe your emulator has limited resources. Really long/large pages have issues displaying on weaker/older devices, try the following to see if it shows up correctly:

* Go to Mihon Settings > Downloads, enable "Split tall images" (this setting is not retroactive, redownload the chapter if it's already downloaded)
* Download the chapter
* Should load up the long/large pages better

Otherwise, another solution is to switch the reading mode to Paged

**Comment by ChanchanReal** [comment]
Okay I was able to fix it by changing the Resolution I am using  720p and change  to 1080p i guess it doesn't support 720p now.
