### ISSUE TITLE
Add select all chapters above or below

### ISSUE THREAD

**Issue by F-shark** [mihonapp/mihon#1465]
### Describe your suggested feature

When selecting chapters add a select all chapters above and a select all chapters below, would save me time, thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Use range selection.

Select one chapter, then scroll to whatever end you want, let's say top. At the topmost chapter, press and hold to select the chapter, then keep holding until all chapters between your first selection and this one is selected. Doesn't need to be the topmost or bottommost chapter, can be any other chapter in between.

Closing as not planned because this feature does the same job, and is more flexible.

**Comment by F-shark** [comment]
Thank you sorry I didn't know about this 🙏
