### ISSUE TITLE
Crash (No crash screen) on chapter open

### ISSUE THREAD

**Issue by mm12** [mihonapp/mihon#1555]
### Steps to reproduce

This only happens on one particular chapter of a particular entry, as far as I can tell. Debug logs attached. 
1. Download Chapter
2. Open Chapter

### Expected behavior

Chapter Loads

### Actual behavior

1. Chapter load spinner starts
2. Entire app crashes (No crash "catch" screen), exits to home screen
3. The residual 'reading mode' toast (eg, left to right) appears 
NOTE: Sometimes, it fails back to the entry instead of out of the app. I will investigate further. Both crash logs are now included.

### Crash logs

Full crash: 
[mihon_crash_logs.txt](https://github.com/user-attachments/files/18056289/mihon_crash_logs.txt)
Entry failback: 
[mihon_crash_logs_menu.txt](https://github.com/user-attachments/files/18056330/mihon_crash_logs_menu.txt)

### Mihon version

0.17.1

### Android version

Android 15

### Device

Google Pixel 8 Pro

### Other details

Verbose logging was ON for this crash log. I restarted the phone, re-downloaded the chapter. Opening in webview renders fine. 
If you would like screencap of this, please @ me on discord

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Considering you say this only happens for one particular entry, please ask your extension maintainers for support first. It may be the case that this extension in particular may need to be updated to account for website changes.

From my glance at the strange crash data, it appears Mihon is crashing because it breaks during image decoding. That usually points towards malformed/misinterpreted data from the source (wrong file type or something for example).
