### ISSUE TITLE
Having trouble reading manhwa/hua in Longstrip.

### ISSUE THREAD

**Issue by 0MikeySano** [mihonapp/mihon#1558]
### Steps to reproduce

I updated my mihon to 0.17.1 but I can't still see any images.

### Expected behavior

This should've been fix after the patch.

### Actual behavior

It still not loading images after the patch.

### Mihon version

0.17.1

### Android version

Android 8

### Device

Vivo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It's not fully fixed for all the old devices having the blank page issue.

For now, try adjusting the bitmap threshold setting in Mihon Settings > Advanced, lower it until it shows (if it shows).

Otherwise:
>>> ### Devices experiencing blank/black pages:
** **
For some older devices, they are unable to handle the really large/long pages sources use:
1. Go to Mihon Settings > Downloads, enable "Split tall images"
    This setting is not retroactive, redownload the chapter if it's already downloaded
2. Download the chapter & try reading it again
    Otherwise, change the reading mode to Paged (if the above doesn't work/you don't want to download)
### Easy download management
* Go to Mihon Settings > Downloads, and enable "Download ahead" paired with "Delete automatically after read"
* This makes it so you only download as you read, reducing unnecessary requests & to easily manage your storage usage

**Comment by MajorTanya** [comment]
> I can confirm this bug is back on my Samsung S7 Android 8.
> Tested on Beta r7031.

Have you tried the steps lined out above? As you have a Samsung Galaxy device running Android 8, the setting mentioned may not be available for you.

**Comment by doudoud82** [comment]
> 
> Have you tried the steps lined out above? As you have a Samsung Galaxy device running Android 8, the setting mentioned may not be available for you.

Yeah, the settings for adjusting the Bitmap threshold are indeed hidden from the advanced settings.

**Comment by arozaqf** [comment]
Have the same probelm, the mentioned step already done but still not displayed properly

**Comment by AntsyLich** [comment]
Fixed with https://github.com/mihonapp/mihon/commit/c5655e8803bc32d0931657f0b7bc6afeab70feaf
