### ISSUE TITLE
Read by volume or by chapter

### ISSUE THREAD

**Issue by GhostSniper2** [mihonapp/mihon#1589]
### Describe your suggested feature

It add an option to choose between read mangas by chapter or by volume

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Mihon has no concept of volumes, only chapters

**Comment by peepincreepin** [comment]
> Mihon has no concept of volumes, only chapters

I think they mean in the trackers. Some tracker sites eg Anilist have the ability to track progress by volume, so the OP is probably suggesting a feature that lets you swap the tracker in Mihon to that for certain series. Because sometimes series are uploaded to sites as entire volumes instead of individual chapters.

I've definitely seen this requested here before, but it may have been under Tachiyomi.

**Comment by peepincreepin** [comment]
Yep: https://github.com/mihonapp/mihon/issues/15

**Comment by GhostSniper2** [comment]
> > Mihon has no concept of volumes, only chapters
> 
> I think they mean in the trackers. Some tracker sites eg Anilist have the ability to track progress by volume, so the OP is probably suggesting a feature that lets you swap the tracker in Mihon to that for certain series. Because sometimes series are uploaded to sites as entire volumes instead of individual chapters.
> 
> I've definitely seen this requested here before, but it may have been under Tachiyomi.

Exactly 👍

**Comment by GhostSniper2** [comment]
> Yep, requested here: #15

Thank's

**Comment by GhostSniper2** [comment]
Request already send
