### ISSUE TITLE
Skip Chapter button

### ISSUE THREAD

**Issue by Void2258** [mihonapp/mihon#160]
### Describe your suggested feature

Since duplicate chapters can occur relatively frequently (different groups), it would be handy to have a skip chapter button while in reading mode. Currently you have to back out and hold to mark chapter as read (or rapid tap through the chapter). This way when you see a duplicate you can fast travel to the next non-duplicate chapter. Should mark the skipped chapter as read and delete it if you have it set to delete as you read (might need a confirmation dialogue).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by elusivesamurai** [comment]
@Void2258
Settings>Reader>skip duplicate chapters option
Also the Scanlator filter from filters of chapter list
Could these be it?

**Comment by Void2258** [comment]
This requires the chapter follow proper formatting to register as the same chapter. This is often not the case, especially is one group releases "chapter 6" while another releases 6.1, 6.2, etc. So we need a manual switch for when the automatic can't catch it.

**Comment by cuong-tran** [comment]
Almost created another issue until I found this.

### the current `Skip duplicate chapters` would mistakenly hides chapters if entry has volumes/seasons in it
A lot of entries have chapters named in form: _Volume - Chapter_ or _Season - Chapter_

When reading, chapters would be skipped and hidden, causing wrongly jump to next chapter. For example reading Season 2 Chapter 03 will jump to next chapter Season 1 Chapter 03/04.

Since the toggle for `Skip duplicate chapters` is in Settings, it is very inconvenient to switch the setting on/off while reading. We don't really know how each source organizes their entries so don't think a fixed setting is no way.

Possible solution:
- Make the Skip duplicate chapters feature smarter to recognize also volume/season number. This would also close #213
- Or if it detects any abnormal in chapter number, it disables itself for that entry.
- Or make a per-entry setting for this Skip duplicate feature.

Or else the Skip duplicate feature would be meaningless.

![image](https://github.com/user-attachments/assets/2681ff22-5d09-4fbd-bcff-1a16cd5bf182)
![image](https://github.com/user-attachments/assets/02638457-3002-4db9-9727-9fc76d232800)

**Comment by BrutuZ** [comment]
> the current Skip duplicate chapters would mistakenly hides chapters if entry has volumes/seasons in it

Mihon only works with chapters, it is oblivious to the concept of Volumes/Seasons, always has been

**Comment by Void2258** [comment]
A lot of responses here are about automation. I am not even suggesting this. I just think there should be a manual button to let you jump to the next chapter with one press without having to rapid-tap through. If group one did chapter 12, then group 2 does chapter 12.1, I should just be able to fast skip until I hit a chapter 13, not have to rapidly page flip.

**Comment by BrutuZ** [comment]
But, there is a Next Chapter button on the progress bar o_0
![Screenshot_20241027_163629_TachiyomiSY](https://github.com/user-attachments/assets/fe50cc7a-527e-4170-9e34-7f3f987f52af)

**Comment by Smol-Ame** [comment]
Since you guys un-necro'd the request, I'll just finally close it (like I've had written in my list for a while)

![Screenshot_20241027_125006_Sheets](https://github.com/user-attachments/assets/b6f889e4-8e5e-49ba-8723-ea8f75abae90)

* As BrutuZ mentioned, the reader already has a Previous & Next chapter button to the left & right of the Page Slider, use that

Plus, you can also just skip duplicate chapters entirely if you want:
* (Per-series) Filtering scanlators for the title (Manga entry > Filter button/three lines button)
* Then go to Mihon Settings > Reader, and turn on "Skip filtered chapters" and/or "Skip duplicate chapters"

![Screenshot_20241027_125356_Mihon](https://github.com/user-attachments/assets/372003d6-4e0c-497d-9cb0-e2b5faf5d0c2)
