### ISSUE TITLE
Include repos in backup

### ISSUE THREAD

**Issue by semiya5** [mihonapp/mihon#250]
### Describe your suggested feature

Include repo settings in backups since the rest are already included

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
They are already included and restored during restoration. Just tested it and it is definitely working.

If you're not seeing them right after restoring a backup, try refreshing the list by pulling down on the extension list, it should appear then. Otherwise, restarting the app after the backup restoration will make it appear, too.
