### ISSUE TITLE
Missing Extensions Show Numbers Instead of Names

### ISSUE THREAD

**Issue by OkyDooky** [mihonapp/mihon#337]
### Steps to reproduce

I [followed the steps](https://keiyoushi.github.io/docs/guides/getting-started#adding-the-extension-repo) to add the extensions back and after installing all the ones I could remember, some are stoll missing. But, when I look in the Migrate tab, it just shows numbers that don't seem to point to any specific extension. :/

### Expected behavior

I expected to see names from the extension list that I could use to install what's missing.

### Actual behavior

Described above.

### Mihon version

0.16.3

### Android version

Android 11 (LineageOS)

### Device

Samsung Galaxy Note 3 T-Mobile

### Other details

Not sure if bug or missing feature or if I somehow did something wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
This is the same behaviour as back in Tachiyomi as the app doesn't store anything other than the source's ID internally (because extensions can change names, URLs, etc, so storing and refreshing that stuff would be a hassle, not to mention sources that support several predefined or even custom URLs).
I don't think this is an actionable issue sadly. I'll close it but you can ask in the Discord if you have further questions. 👍

**Comment by OkyDooky** [comment]
I figured there was some disconnect somewhere. But, I guess I figured that could be overcome by comparing the ID value with that of the extension repo's list. Isn't that where the value was derived in the first place? If that's then case, then I'd like to open a feature request to have Mihon support ID comparison checking for extensions not installed with those of any added repositories. If not, then I guess I'll just have to do all the migrations by hand or something (unless there's a more automated way?). But, it still would be nice for some way to minimize this happening to anyone in the future.
For reference, this is what I am looking at (probably should have included this in the OP):
![Screenshot_20240203-163744_Mihon](https://github.com/mihonapp/mihon/assets/59938024/47dfc21f-9f84-40c3-8bed-bbfd9f70d2c4)
![Screenshot_20240203-163853_Mihon](https://github.com/mihonapp/mihon/assets/59938024/0c98edc1-9dfb-4b6c-9f26-fe3ddcae7c1c)

**Comment by Efreak** [comment]
@OkyDooky *some* of these can be found by searching the web iirc. You can also check if TachiyomiSY/other fork saves the source name, because that might be a copyable feature if it's already implemented; I have the vague idea that one of the forks is doing this, but I can't recall which and I might well be misremembering.
