### ISSUE TITLE
Provide a build without Google's SDK

### ISSUE THREAD

**Issue by cohesive-flight** [mihonapp/mihon#338]
### Describe your suggested feature

Since you don't plan on adding the app to F-Droid, could you provide an additional build without Google's SDK? It would be fully FOSS and beneficial privacy-wise.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Mihon uses Google analytics to know info like user count, Android version, app version etc. which can be used to make decisions like dropping an android version because negligible amount of people use them. As such I won't be making a build without it. Chances are I might move to some FOSS analytics alternative (e.g. [plausible/analytics](https://github.com/plausible/analytics)) but that isn't happening anytime soon. If you believe privacy invasive info are being harvested then let us know and we'll take a look.
