### ISSUE TITLE
Library covers (japscan)

### ISSUE THREAD

**Issue by Pestenxir** [mihonapp/mihon#351]
### Steps to reproduce

1.go on japscan sources 2. Refresh a manga

### Expected behavior

Covers should be the manga cover

### Actual behavior

The covers are replaced by the ads and not the actual manga covers 
![Screenshot_20240206-032511_Mihon](https://github.com/mihonapp/mihon/assets/141491623/4f2fc777-4b8b-45aa-beed-ed16a5988cbc)

### Mihon version

App version: 0.16.3 (standard, 139663a, 4, 2024-01-29T20:34Z) Android version: 11 (SDK 30; build RP1A.200720.012.A505FNXXU9CWB4) Device brand: samsung Device manufacturer: samsung Device name: a50 (a50eea) Device model: SM-A505FN WebView: Android System WebView 121.0.6167.101

### Android version

Android 11

### Device

Galaxy a50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Extension issue and Mihon cannot and will not provide support for issues specific to extensions. Go ask whoever made this extension to fix it.

**Comment by Efreak** [comment]
@MajorTanya commenting here semi-related since I see a few source-related issues here and I believe you'll get a number of them in the future:

You might consider updating the issue template. 
- I recommend removing the *I have updated all installed extensions* item (this is irrelevant. Honestly not sure why updates for unrelated extensions would matter even if you were supporting extensions)
- add *this is not an extension issue*. Maybe move it to the top of you get a lot of these issues. It's questionable if this will actual help, but it shouldn't hurt 🤷
- *I have searched the __existing issues__* can also be converted to a link like others do.

A github action can validate that users have checked the correct boxes and automatically close issues when necessary. There's already an action doing related things here, IIRC you can look for a `[x]` or `[ ]` to determine if a box is checked or unchecked, looking for an unchecked box should be sufficient to tell you that the user hasn't responded to one (all) of the items.
