### ISSUE TITLE
Automatic update not working

### ISSUE THREAD

**Issue by Thibaut-tech** [mihonapp/mihon#361]
### Steps to reproduce

open app 

### Expected behavior

App rafresh and update library

### Actual behavior

Nothing i have to refresh manually my library

### Mihon version

0.16.3

### Android version

Android 13

### Device

S20FE 5G

### Other details

All my library is on a folder name "update".
Automatic update is enable and set to 12 hours.
In smart update all is unchecked

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Xori71** [comment]
Holy shit, **_please_** enable at least the second and third parameter for smart updates and change the update frequency to at least one day. You are a walking DDoS attack!

**Comment by Thibaut-tech** [comment]
I'll try that and see tomorrow if it updates automatically.

**Comment by Thibaut-tech** [comment]
Nope its still not working chapter not update automatically.

**Comment by drybonesification** [comment]
Kind of in the same boat, have issue where update tab won't update anything but when refreshing the manga when on the overview page it works, don't know if this should be a new thread

**Comment by Xori71** [comment]
> Kind of in the same boat, have issue where update tab won't update anything but when refreshing the manga when on the overview page it works, don't know if this should be a new thread

https://mihon.app/docs/faq/updates/smart

**Comment by Smol-Ame** [comment]
Since they un-necro'd the issue, going to do a summary & close out this issue as user-error/not understanding app features.

For the author's issue, since you adjusted Smart Updates & it still wasn't updating, sounds like either you were having source-related issues (dead/down source), extension-related issues (check with whoever maintains your extensions instead for these), or internet-related issues (maybe blocked site, only check when WiFi, etc).

For anyone else, this sounds like you don't understand how Smart Updates work, so here's a semi-quick summary.
* Smart Updates, see link above from Xori71, manages what gets checked during Automatic Updates & Library/Category Updates (including the refresh button in the Updates page)
* This reduces unnecessary requests sent to sources & spreads out your updates over per-series predicted release patterns.
 * You can view the status of prediction/when it'll check for a new update if you go to the manga entry, and tap on the hourglass icon.
* This is done to reduce the chance of sources blocking you, breaking your extensions, and/or go after whoever maintains your extensions/the app itself.
* Make sure Automatic Updates is enabled in your Mihon Settings > Library page, then leave it alone, let it update by itself & adapt over time.
* Otherwise, if there's something you really want to read, and know it has a new chapter, then refresh the entry yourself.
