### ISSUE TITLE
Anime streaming support like Aniyomi (Tachiyomi fork)

### ISSUE THREAD

**Issue by goliv04053** [mihonapp/mihon#370]
### Describe your suggested feature

Anime sources and streaming function for Mihon

### Other details

Aniyomi is a fork who has this feature. Why do not colaborate or even plan to merge both projects in the future?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
No, Mihon is for manga.

**Comment by goliv04053** [comment]
@MajorTanya Mihon subtitle isn't "Discover and read manga, webtoons, comics, and more"? Why shouldn't have a discussion about adding features to today main fork of the old Tachiyomi? Uniting development teams and merging features from other forks to make a fully fledged multimedia application who not only is Manga, Webtoons, Comics... why not Movies, Anime? What can we think more that would be compatible with the project?

**Comment by MajorTanya** [comment]
Because Mihon is not intended to be something other than a reading app - just use two apps for two completely different purposes, as everyone else already does.

As for technical reasons, I don't think any such "fork" would be easily compatible with Mihon's code in the first place at this point, as the requirements for each use case are wildly different. The maintenance burden would also increase to unfeasible levels, considering there are no dedicated, full-time developers on Mihon and it's a mostly community-driven project.

A no is a no. You're welcome to try and bring this up in the Mihon Discord, but I'm pretty sure you will get the same answer there.

**Comment by goliv04053** [comment]
I understand. I used for some time Tachiyomi and Aniyomi but the thing is... for Android. Both apps had basically... the same function but Aniyomi had Streaming functions but I prefered to use Tachiyomi as a Manga reader. That time I asked myself... why it's not possible to have both merged into one and two things at the same app? 

About the technical reason, Mihon is still beginning and the old Tachiyomi developer core team isn't collaborating anymore since that copycrapt*/sue threat stuff. But, why not invite or comment to the fork developers and try (in the future) to build bridges? It would be amazing to see forks getting merged into one to make the ultimate app of all time.

Well, how you said: "A no is a no.". I respect your stance about this idea. Hope that this discussion can come back into a later future. Not now, but in the feature. Thank you for your comment. Have a nice day... or night???  Sorry, here is 4 AM where I live. 😅

Also, sorry if I sounded rude in some way writing this issue (Feature Request).

**Comment by CrepeTF** [comment]
Doing multiple things in a lacklustre way is not as good as doing a single thing in a good way. This way Mihon can focus on just being a good reader rather than having to seesaw its development between two different objectives.

Not to mention how much more bloated the app and settings would be too.

**Comment by AntsyLich** [comment]
"Jack of all trades, master of none"
