### ISSUE TITLE
AniList tracking produces a lot of HTTP 429 errors

### ISSUE THREAD

**Issue by Ogloppi** [mihonapp/mihon#372]
### Steps to reproduce

Generally it goes something like this:

1. Login to AniList tracking through Mihon
1. Try to add or modify AniList tracking for an entry in your library
    1. This should take a long time
1. Get presented with a HTTP 429 error

### Expected behavior

I should be able to add or modify AniList tracking for my entries without delay and HTTP 429 error.

### Actual behavior

99% of the time I get presented with a HTTP 429 error and nothing else happens.

### Mihon version

0.16.3

### Android version

Android 12 (MIUI 14.0.5.0)

### Device

Redmi K30 Pro Zoom Edition

### Other details

I must say that I'm not sure if it's Mihon itself or AniList API causing this.

I have tried to logout and login from AniList tracking through Mihon, and it somehow works for a while (as in no HTTP 429 errors), but after a while the errors come back.
This has happened three times already.

If I consistently try to add an entry or modify it, the action might go through. Maybe 1 out of 20-30 tries works but it only seems to do a single step. E.g. when trying to add tracking to an entry, the search might present you with results to pick from, but when you actually tap a result and try to add it to the entry it will most propably fail to do so.

I have already tried the following other methods while trying to solve this issue:

- Clear the Android application cache -> Try to add or modify entries
- Logout -> Clear cookies and WebView data from Mihon settings -> Login

Here's a screenshot while trying to add an entry to AniList tracking:

![1707508105277](https://github.com/mihonapp/mihon/assets/10729783/dc3f957c-ddb2-4dc2-ae24-f0a1677d71d2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Ogloppi** [comment]
I investigated the AniList side of things and apparently they have server issues. Here's the full quote from their Discord [message](https://discord.com/channels/210521487378087947/457951807046549525/1186703137361383495):

> 19/12/2023
> Due to ongoing server issues, we have temporarily disabled both search and the public API. This means that third party applications will not work at this time. 
> 
> The site will remain up in limited capacity. 
> 
> We are looking into the issues, but there is not currently an ETA on returning to full operational status.

So I'll close this, as this is clearly not a Mihon issue.

**Comment by MajorTanya** [comment]
HTTP error 429 are rate limits, meaning you are (or rather, Mihon is) making too many requests.
Sometimes, this can be caused by many backed-up tracking updates trying desperately to get through. Repeatedly trying to add something manually adds to the pressure on the rate limit.

The best approach is to let it rest for a while until all those background requests have had their turn (might take some time but no data loss).

If you want to get a clean slate and lower your backed-up requests, you can try the following approach, although it's a little bit of work and can take some time, depending on the size of your library:
1. **Create a new, full Mihon backup**
2. Go to the Mihon app settings (not in the app, the phone's)
3. Select "Clear App Data" (this will wipe Mihon, hence making a backup first)
4. Go through Mihon's Onboarding flow again, selecting the same storage location as you had before (downloads survive this wipe)
5. Log in to your trackers (like AniList)
6. (optional at this stage) Trust any extensions currently installed
7. Restore your backup from Step 1
8. If you didn't trust your installed extensions in step 6, do so now 👍 

This will delete the backed-up tracking updates, so you may lose a chapter or two of tracker progress on the occasional title, but if you can endure that, you now have a clean start. Ideally, don't try to make too many tracking changes at once now 😄
