### ISSUE TITLE
Manual Update Not working 

### ISSUE THREAD

**Issue by SoumickDeyArgha** [mihonapp/mihon#427]
### Steps to reproduce

1. Manually Updating the Library (Pulling Down)
2. Exit the app / Move to a different app
3. After some time the Notification Disappears along with any result (New Chapter Found, Skipped, Update Failed etc.)

### Expected behavior

When Updating manually it should show the result when the update is finished
(New Chapter Found, Skipped, Update Failed etc.)

### Actual behavior

Manually Updating the Library (Pulling Down), shows on the Notification the update in progress, then when exiting the app or Moving to another app, after some time the notification disappears along with any result (New Chapter Found, Skipped, Update Failed etc.)

### Mihon version

0.16.3

### Android version

Android 13

### Device

Realme GT Master Edition 

### Other details

I have Disable battery Optimizations and the app has all the permissions.
I tried Uninstalling and reinstalling the app but the behaviour is the same, 
This occurs 8/10 times when I do manual updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
It sounds like you're getting limited by Mihon's predictive updates feature.

Basically, in order to reduce source load and unnecessary requests, Mihon looks at the recent few chapter uploads for a given series and calculates the approximate interval/schedule of uploads.

Then it doesn't ask the source for new chapters (even during manual library updates) unless this calculated interval of time has passed.
This also doesn't give you a notification of skipped series, which is why your updates are done very fast and don't leave any notifications behind.

If you know for some other reason (say, a friend) that a new chapter has come out ahead of this interval, you can go to the title page and update that manually, which bypasses the interval.
