### ISSUE TITLE
[Question] what about a play store build now?

### ISSUE THREAD

**Issue by SViN24** [mihonapp/mihon#49]
### Describe your suggested feature

Right now mihon does not provide extensions on services that infringe your copyright and the user must provide his or her own material. Similarly to many emulators on the play store.

Is there something that blocks a release on the play store now?(possibly the fact that the application needs to install apks?)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by dev0T** [comment]
I'd rather have it on F-Droid.

**Comment by EnderShadow** [comment]
Could always put it on both

**Comment by mostidaniel** [comment]
Yea, I think to do this, the ability to add third party extensions repo would need to be removed, at least for the Play Store version, since the [Google Play Store policy on Device and Network Abuse](https://support.google.com/googleplay/android-developer/answer/9888379?hl=en&ref_topic=9877467#zippy=%2Cexamples-of-common-violations) prohibits any application from downloading an executable code from sources other than Google Play. Furthermore, [the app updater functionality would also need to point to Google Play](https://support.google.com/googleplay/android-developer/answer/9888170?visit_id=638410325693227537-2395121516&rd=1#:~:text=The%20REQUEST_INSTALL_PACKAGES%20permission%20may%20not%20be%20used%20to%20perform%20self%20updates%2C%20modifications%2C%20or%20the%20bundling%20of%20other%20APKs%20in%20the%20asset%20file%20unless%20for%20device%20management%20purposes.) instead of GitHub.

**Comment by SViN24** [comment]
Well the app update functionality being disabled is normal and I think it's also done for the fdroid release

**Comment by SViN24** [comment]
I'm also not sure what the limits are for said executable code.

Minetest on playstore can download entire mod packs.
And a far more similar application kodi also has download able extentions directly through the play store app.

Probably the issue is the fact that mihon downloads apks making it similar to an appstore, that and it can install "third party extensions"

**Comment by CodeSpoof** [comment]
Simple way would be to do it via IzzyOnDroid's F-droid repo. Would only need disabled update and updates get out faster than via oficial f-droid

**Comment by Seishirou101** [comment]
Probably won't happen for either playstore or f-droid. see previous [reply](https://git.mihon.dev/tachiyomi/tachiyomi/issues/6736#issuecomment-22456)
