### ISSUE TITLE
install all or uninstall all extentions button

### ISSUE THREAD

**Issue by MarshMeadow** [mihonapp/mihon#53]
### Describe your suggested feature

i would like a button to install or uninstall extensions because I have all or to many from the og app and I wanna start over

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by dtantono** [comment]
it will be good, if we have a toggle to trust anything under that repo link

**Comment by MajorTanya** [comment]
I'm not sure this would be possible considering uninstalling is handled by the OS (depending on the package install method used), not by anything Mihon does directly.

**Comment by AntsyLich** [comment]
Install All: Why?
Uninstall All: As extensions are install to android like any other app you should just use some already existing app to mass uninstall them.

**Comment by mqwec43as** [comment]
Maybe installing every missing extensions would be more useful?

Missing extensions should fulfill the following criterias:

1. Not installed.
2. An entry from the extension found in the library.
3. The extension found in the registered extension repos.

I guess the principle would be very similar to "Update All" but it goes for every missing extensions. "Install Missing Extensions."

This way user would have the option to install only relevant sources with a single action.

I think this should be safe option since the user previously used the extension already. Maybe there has to be another security layer, like verifying that the extension is retrieved from the same repo as the missing one.

**Comment by MajorTanya** [comment]
Is it even possible to bulk install apps through Android's package management?
