### ISSUE TITLE
Description bug

### ISSUE THREAD

**Issue by HokuJJK** [mihonapp/mihon#542]
### Steps to reproduce

Description in the library is always hidden; description in search is always open.

### Expected behavior

It must be either in the open position or in the closed position

### Actual behavior

In one place in a hidden position in another in an open position

### Mihon version

0.16.4

### Android version

Android 12

### Device

Poco F5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by sirlag** [comment]
Do you have screenshots of this behavior? Make sure the source names are hidden.

**Comment by sirlag** [comment]
@Norsze Oh. That took me *way* more time than I want to admit poking around the app even with that description to see what this was about. I haven't noticed that in years. I think the intended behavior also makes a ton of sense, since when searching you would presumably want to know the description vs something you are already familiar with
