### ISSUE TITLE
Incorrect tap location on Fire Tablets

### ISSUE THREAD

**Issue by RayW1986** [mihonapp/mihon#70]
### Steps to reproduce

Use the app on a Fire tablet.

### Expected behavior

Tapping the screen should register where you've actually tapped. 

### Actual behavior

This issue started with Tachiyomi 0.15.0, but since that update when using a Fire device, screen touches are not registering correctly. It's as though it's a touch behind? It's hard to explain so I have attached a video.

https://github.com/mihonapp/mihon/assets/7612076/171a5cdf-ca24-4e4e-a970-960ea5e73de1

You can see when I click downloaded its fine, but then when I click unread it toggles downloaded. It is like this throughout the app.

### Mihon version

0.16.0

### Android version

Androidn11

### Device

Fire Tablet Max 11 / Fire HD 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kazuhachuli** [comment]
I have a problem that also started in Tachiyomi 0.15.0, mine is a little different, when you swipe back with gesture(right to left or left to right) to go at Home (Android Desktop) the animation doesn't work, It's like it closed in the blink of an eye.

**Comment by david79111** [comment]
I have the same problem with incorrect touches on my fire hd 10 2023 android 11/latest fire os build

**Comment by kazuhachuli** [comment]
> This issue started with Tachiyomi 0.15.0, but since that update when using a Fire device, screen touches are not registering correctly. It's as though it's a touch behind? It's hard to explain so I have attached a video.

Really? First person that have my same problem, try swipe from bottom to top and the animation will work, can you do a video of the problem pls?

Also im at Poco x3 pro android 13/miui 14

**Comment by DannyFestor** [comment]
I have the same issue with taps are one tap behind on the Kindle Fire HD 10 (13th Gen), Fire OS 8 (latest version). I don't know how to solve this, but I have the same phenomenon in 2 other apps:

- Proton Drive (Dropbox alternative by Proton Mail)
- Google Play Store (curiously, but not unexpected because Google Services are unsupported on Fire OS...)

I think this might be a tooling problem (Java/Kotlin version?) rather than a Mihon specific bug.
I can't find anything on the internet concerning this problem except for this thread, really.

When looking through the update commit I found 
- Java version was bumped from 1.8 to 17. (build.gradle.kts)
- Kotlin version was bumped from 1.8.0 to 1.9.21 (gradle/kotlinx.versions.toml)

**Comment by sfai05** [comment]
Have the same issue on Fire Max 11 (13th Gen) with Fire OS 8.3.2.2

**Comment by Wylie03** [comment]
I am currently having this issue on Fire HD 10 13th gen as well. Has anyone found a fix yet?

**Comment by KevPantelakis** [comment]
Same issue here with me Mihon and Google Play on a Fire HD 10 13th gen (2023)

**Comment by doodleboink** [comment]
I have the same issue. Fire Max 11.
Enabling pointer location shows that it isn't an issue with the touch data, it's something to do with how that data is passed to certain apps.

**Comment by DannyFestor** [comment]
By the way, I don't have the bug in the preview version v6695 (previous) and v6697 (latest). Here's to hoping that whatever fixed it in the preview version gets quickly brought into stable.

(I have only tested these 2. No idea how long it is fixed over in the preview.)

**Comment by kakai248** [comment]
I found this thread because I also hit this issue at work. Just to leave some more information here, this stopped happening on Compose 1.7.0 (alpha versions). Compose 1.5.4 and 1.6.7 exhibit the problem.

**Comment by elfez** [comment]
Can confirm this is resolved for me in Preview r6793. This is also on a Kindle Fire HD 10 (2023).

**Comment by Smol-Ame** [comment]
Since Mihon Stable is now on the same Compose version as the last Preview, this issue should be resolved. If you are still experiencing this issue on the latest Mihon Stable/Mihon Preview version, make a new issue request about it (include a screen-recording of the issue along with the version info).
