### ISSUE TITLE
FOSS build with non-free stuff on top?

### ISSUE THREAD

**Issue by opusforlife2** [mihonapp/mihon#758]
### Describe your suggested feature

Hi. There are many apps, such as [Librera](https://github.com/foobnix/LibreraReader), which have a completely FOSS build to start out, and then add stuff like Play Services integration and ads for the Play Store version on top.

This allows F-Droid to package the app easily, and the developer is free to change the non-free/proprietary code to suit their purposes, whether it's for ads, tracking or analytics.

Is it possible for Mihon to go the same route? Or is the code too complicated and infeasible to adjust for this? Since there are real world examples of this, it should be possible theoretically, at least.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No intention to support F-Droid builds so I see no point to this

**Comment by AntsyLich** [comment]
F-Droid support will require the removal of junrar. junrar is needed to support RAR files. Being able to read from rar or cbr files a core feature of the app

**Comment by FooIbar** [comment]
Maybe rewrite the archive part with https://github.com/zhanghai/libarchive-android in the future
Better performance, RAR5 support, and FOSS

**Comment by MajorTanya** [comment]
> > F-Droid support will require the removal of junrar.
> 
> @AntsyLich You don't need to remove _anything_. That is the entire reason why I opened this issue. The proprietary stuff can exist as a layer on top of the FOSS code, and simply not be built for the FOSS flavour. Again, please refer to https://github.com/foobnix/LibreraReader as an example. Its Play Store version has ads, and yet it's available on F-Droid as a fully FOSS app.

From my incomplete knowledge of the codebase, I believe junrar is used to handle RAR compressed files of chapters, particularly for the local source. Using Librera's approach (again, from my cursory look through their Gradle scripts) would mean Mihon has to somehow flag the handling of RAR archives as non-fdroid, most likely making that unavailable on those releases.

At that point it would in fact be a lot easier to do what Foolbar suggested and replace it, assuming that linked library above can be slotted into Mihon with reasonably minimal effort.

I personally don't fully understand the perceived urgency of the matter either, since anyone can fork Mihon if they desire to change something about it that Mihon does not currently want to/have the time/ability to change.

I understand that you and others care about an Fdroid release even if others don't, but if push came to shove, that fork option would be on the table.

**Comment by AntsyLich** [comment]
> @AntsyLich You don't need to remove _anything_. That is the entire reason why I opened this issue. The proprietary stuff can exist as a layer on top of the FOSS code, and simply not be built for the FOSS flavour.

That's a fancy way to say I need to remove a core feature to support F-Droid

**Comment by BrutuZ** [comment]
Honest question: what would be the point of having it on F-Droid? More visibility, automatic updates? The current model has both of those covered.

**Comment by AntsyLich** [comment]
Regardless no intention to support a F-Droid build. If someone wants to they can make a build themselves
