### ISSUE TITLE
More frequent global automatic update options

### ISSUE THREAD

**Issue by AeraDawn** [mihonapp/mihon#79]
### Describe your suggested feature

More time length options <12 hours for the global automatic update function. (1 hour, 3 Hours, 6 Hours, etc.)

I like to do a global update every 3 hours or so personally, so I get notified throughout my work day of new chapters. It's not a huge hassle to open it and do it myself, but having it do so automatically would be nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TheColorman** [comment]
I think there did used to be more frequent update options, but they've been changed to reduce the load on extensions. Some sources would usually block extensions every few days because peoople using Tachi kept spamming updates, so changes such as reducing the number of updates per day and features such as not updating entries with unread chapters and the newer release predictions have been added to reduce the load on popular extensions.

**Comment by AntsyLich** [comment]
No
