### ISSUE TITLE
Addition of Confirm Exit toggle

### ISSUE THREAD

**Issue by SaisuryaL** [mihonapp/mihon#91]
### Describe your suggested feature

Tachiyomi had a confirm exit toggle which is currently missing in Mihon. It would be good to have the option to prevent accidentally exiting the app while swiping back.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
(my comment copied from #173 where I commented before seeing this issue)

This feature was removed in https://github.com/mihonapp/mihon/commit/8f4bc71cf7b99fe0b0d2ea68dfca0140477686cc because it was deemed redundant with Android's Predictive Back feature when using gesture navigation, just to assure you it used to exist. 👍

I don't know if there would be a way to bring this feature back that doesn't clash with this predictive back feature, though, so I can't give you a definitive yes/no on whether it can be brought back.
